# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KKBVideoPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KKBVideoPlayer
    pod 'Bond','~> 7.8.1'

end
