# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'DCUIFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DCUIFramework

end

target 'TestUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestUI

end
